-- ─────────────────────────────────────────────────────────────────────────────
-- 023 · O NÚMERO DO RECIBO E A CÓPIA DO COMPROVANTE
--
-- ★ POR QUE ESTA MIGRAÇÃO EXISTE: o sandbox da Rebots respondeu, em 25/08/2026, duas coisas
-- que a documentação pública não dizia — e cada uma quebra o 020 de um jeito diferente.
--
--   1 · `receipt_id` é INTEIRO. Mandávamos o `id` da linha do razão, que é `uuid`, e a API
--       devolve `RECEIPT_ERROR_024 invalid literal for int()`. Toda emissão falhava.
--
--   2 · A `file_url` do PDF vale CINCO MINUTOS (presigned S3, `X-Amz-Expires=300`) — não 48h,
--       como estava escrito. E a API deles não tem consulta: nenhum GET, em nenhum endpoint.
--       Somados, os dois fatos dizem que o PDF só existe durante a chamada do callback.
--
-- ⚠️ RODE O 020 ANTES. Esta migração altera a `abrir_recibo_unitario` que ele criou.
--
-- Idempotente: pode rodar duas vezes.
-- ─────────────────────────────────────────────────────────────────────────────

-- ─────────────────────────────────────────────────────────────────────────────
-- 1 · numero — o inteiro que a linha do razão passou a precisar ter
--
-- ★ ELE É O PROTOCOLO, e por isso é `identity` e não um `nextval` avulso: o número tem que
-- nascer na MESMA transação que prende o pagamento. Um contador pedido depois, pelo adaptador,
-- devolveria o número só quando o canal já tivesse aceitado — reabrindo exatamente a janela do
-- `pendente` sem protocolo que o 020 fechou (ver `precisaDeOlhoHumano`).
--
-- ⚠️ É GLOBAL, NÃO POR INQUILINO, e isso não é descuido. O `tenantDoProtocolo` do callback
-- consulta por `canal` + `protocolo` SEM filtrar inquilino — a finalidade dela é justamente
-- PRODUZIR o inquilino. Numeração por inquilino faria dois negócios terem o protocolo "1", e a
-- consulta que resolve o dono do recibo passaria a achar duas linhas.
-- ─────────────────────────────────────────────────────────────────────────────

alter table public.recibos_emitidos
  add column if not exists numero bigint generated by default as identity;

/* Redundante com a sequência, e de propósito: a sequência garante o próximo valor, não a
 * unicidade da coluna. Um `insert` que passe `numero` explícito (script de correção, restore
 * parcial) fura a sequência e não fura o índice. */
create unique index if not exists recibos_emitidos_numero_unico
  on public.recibos_emitidos (numero);

comment on column public.recibos_emitidos.numero is
  'O protocolo, quando o canal exige inteiro — o `receipt_id` da Rebots é `int`, e recusa uuid '
  'com RECEIPT_ERROR_024. Nasce na mesma transação da claim para o protocolo existir ANTES da '
  'chamada ao canal. Global de propósito: `tenantDoProtocolo` consulta sem filtrar inquilino.';

-- ─────────────────────────────────────────────────────────────────────────────
-- 2 · comprovante_caminho — a exceção à regra "URL, nunca o arquivo"
--
-- ⚠️ ESTA COLUNA CONTRADIZ O QUE O 020 ESCREVEU, e a contradição é deliberada. O 020 dizia:
-- "URL, NUNCA O ARQUIVO — guardar o binário seria virar depositário de prontuário financeiro
-- de terceiros". O raciocínio estava certo para uma URL de 48h. Para uma de cinco minutos ele
-- leva a outro lugar: "não guardar" deixou de significar "ela baixa quando quiser" e passou a
-- significar **o documento não existe para ninguém**. E o PDF oficial é a única coisa que o
-- canal pago entrega e o lote CSV não.
--
-- Os LIMITES em que a exceção vale, e fora deles ela não vale:
--   · bucket PRIVADO. Nunca `public = true`, nunca URL permanente — link assinado na hora.
--   · caminho prefixado pelo inquilino, e a política de leitura confere o prefixo.
--   · é o documento fiscal DA DONA, cujo CPF de paciente o razão já guarda para poder emitir.
--     A cópia acrescenta um arquivo, não uma categoria nova de dado.
--   · sem política de DELETE para membro: linha do razão não se apaga, arquivo do razão também
--     não. Expurgo, se um dia houver, é rotina de serviço com prazo escrito.
-- ─────────────────────────────────────────────────────────────────────────────

alter table public.recibos_emitidos
  add column if not exists comprovante_caminho text;

comment on column public.recibos_emitidos.comprovante_caminho is
  'Caminho da NOSSA cópia do PDF no bucket `comprovantes-recibo`. Existe porque a file_url do '
  'canal vale 5 minutos e não há endpoint de consulta: fora da janela do callback o documento '
  'seria irrecuperável. `pdf_url` continua guardada, mas só serve para auditoria.';

-- ─────────────────────────────────────────────────────────────────────────────
-- 3 · o bucket
-- ─────────────────────────────────────────────────────────────────────────────

insert into storage.buckets (id, name, public)
values ('comprovantes-recibo', 'comprovantes-recibo', false)
on conflict (id) do update set public = false;

/* ⚠️ `public = false` NO `do update` de propósito: se alguém marcar o bucket como público pelo
 * painel, rodar esta migração de novo desfaz. Bucket público aqui é o CPF de um paciente numa
 * URL que não expira. */

/* Leitura: só membro do negócio dono do caminho. `foldername(name)[1]` é o primeiro segmento —
 * o `tenant_id`, como o adaptador escreve. Sem esta política, o bucket privado só é legível
 * pela service role, e a tela nunca conseguiria oferecer o download. */
drop policy if exists "membro lê comprovante" on storage.objects;
create policy "membro lê comprovante" on storage.objects
  for select to authenticated
  using (
    bucket_id = 'comprovantes-recibo'
    and (storage.foldername(name))[1] in (
      select public.negocios_do_usuario()::text
    )
  );

/* ⚠️ NÃO HÁ POLÍTICA DE INSERT, UPDATE OU DELETE PARA `authenticated`, e a ausência é a regra.
 * Quem escreve aqui é o callback, que roda como `ator: sistema` e portanto com service role
 * (ver `contexto-cliente.ts`). Dar insert a membro deixaria a dona — ou qualquer sessão dela —
 * subir um PDF qualquer no lugar do comprovante que a Receita emitiu. */

-- ─────────────────────────────────────────────────────────────────────────────
-- 4 · abrir_recibo_unitario() — agora devolve o número
--
-- `drop` antes do `create`: mudou o tipo de retorno, e o Postgres não deixa `create or replace`
-- trocar a assinatura de saída. Recriada idêntica ao 020 no resto — a única diferença é o
-- `numero` no `returns table` e no `return query`.
-- ─────────────────────────────────────────────────────────────────────────────

drop function if exists public.abrir_recibo_unitario(uuid, text, uuid, text);

create function public.abrir_recibo_unitario(
  p_tenant_id uuid,
  p_fonte     text,
  p_id        uuid,
  p_canal     text
)
returns table (
  recibo_id uuid,
  numero    bigint,
  valor     numeric
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_recibo uuid;
  v_numero bigint;
  v_valor  numeric;
  v_achou  boolean := false;
begin
  if p_fonte not in ('atendimento', 'avulso') then
    raise exception 'fonte desconhecida: %', p_fonte;
  end if;

  /* Antes do insert, para a mensagem ser legível. Sem isto o erro que sobe é violação de
   * CHECK constraint, que na tela do dono não quer dizer nada. */
  if p_canal not in ('automacao', 'rebots', 'lote_csv') then
    raise exception 'canal desconhecido: %', p_canal;
  end if;

  /* ── tranca a fonte ──
   * O valor sai do BANCO, nunca de quem chama: tela aberta há dez minutos manda total velho,
   * e aqui o total velho viraria um recibo de valor errado — documento fiscal torto que só se
   * conserta cancelando. Mesma regra de `abrir_nota`. */
  if p_fonte = 'atendimento' then
    select a.servico_valor into v_valor
      from public.atendimentos a
     where a.tenant_id = p_tenant_id
       and a.id = p_id
       and a.lote_recibo_id is null
       and a.recibo_id is null
       and a.situacao = 'marcado'
       and a.inicio < now()
       for update skip locked;
    v_achou := found;
  else
    select q.valor into v_valor
      from public.pagamentos_avulsos q
     where q.tenant_id = p_tenant_id
       and q.id = p_id
       and q.lote_recibo_id is null
       and q.recibo_id is null
       for update skip locked;
    v_achou := found;
  end if;

  /* Já preso por outro canal, ou segunda aba. NÃO é erro — quem chama responde "já foi". */
  if not v_achou then
    return;
  end if;

  /* ★ O `numero` VOLTA DAQUI, da mesma transação que prendeu. É isso que faz o protocolo ser
   * conhecido antes de qualquer chamada ao canal. */
  insert into public.recibos_emitidos (tenant_id, canal, situacao)
  values (p_tenant_id, p_canal, 'pendente')
  returning id, recibos_emitidos.numero into v_recibo, v_numero;

  if p_fonte = 'atendimento' then
    update public.atendimentos set recibo_id = v_recibo
     where tenant_id = p_tenant_id and id = p_id;
  else
    update public.pagamentos_avulsos set recibo_id = v_recibo
     where tenant_id = p_tenant_id and id = p_id;
  end if;

  return query select v_recibo, v_numero, coalesce(v_valor, 0);
end;
$$;

comment on function public.abrir_recibo_unitario is
  'Tranca um pagamento e cria a linha do livro-razão, na mesma transação. Devolve zero linhas '
  'quando o pagamento já está preso por outro canal — o que não é erro. O `numero` sai daqui '
  'porque o protocolo tem que existir antes da chamada ao canal.';

-- ─────────────────────────────────────────────────────────────────────────────
-- 5 · conferência
-- ─────────────────────────────────────────────────────────────────────────────

do $$
declare
  v_numero int;
  v_comprovante int;
  v_bucket int;
  v_func int;
begin
  select count(*) into v_numero
    from information_schema.columns
   where table_schema = 'public' and table_name = 'recibos_emitidos' and column_name = 'numero';

  select count(*) into v_comprovante
    from information_schema.columns
   where table_schema = 'public' and table_name = 'recibos_emitidos'
     and column_name = 'comprovante_caminho';

  select count(*) into v_bucket
    from storage.buckets where id = 'comprovantes-recibo' and public = false;

  /* Confere que a função devolve TRÊS colunas — o sintoma de a migração ter rodado pela metade
   * é `abrir` continuar devolvendo duas, e aí a emissão volta a mandar uuid. */
  select count(*) into v_func
    from information_schema.parameters
   where specific_schema = 'public'
     and specific_name in (
       select specific_name from information_schema.routines
        where routine_schema = 'public' and routine_name = 'abrir_recibo_unitario'
     )
     and parameter_mode = 'TABLE';

  raise notice '023 · numero: %/1 · comprovante_caminho: %/1 · bucket privado: %/1 · colunas de retorno da abrir_recibo_unitario: %/3',
    v_numero, v_comprovante, v_bucket, v_func;
end $$;
